name = "khadamat"
compatibility_date = "2025-07-20"

# يخبر Cloudflare أن ملفات الواجهة الأمامية موجودة في مجلد public
pages_build_output_dir = "public"

# يربط قاعدة البيانات بالخادم الخلفي
[[d1_databases]]
binding = "DB"
database_name = "main_database"
database_id = "e0efb93b-1a2e-4131-b172-2c81985f9d02"