name = "khadamat"
compatibility_date = "2025-07-20"

# يخبر Cloudflare أن ملفات الواجهة الأمامية موجودة في مجلد public
pages_build_output_dir = "public"

# يربط قاعدة البيانات بالخادم الخلفي
[[d1_databases]]
binding = "DB"
database_name = "main_database"
database_id = "e0efb93b-1a2e-4131-b172-2c81985f9d02"
# ================================================
# ✅ NEW: Durable Object binding for Live Chat
# This enables real-time chat rooms.
# ================================================
[[durable_objects.bindings]]
name = "LIVE_CHAT_ROOM"
class_name = "LiveChatRoom"

[[migrations]]
tag = "v1" # Required for Durable Objects
new_classes = ["LiveChatRoom"]