# =========================================================
#  ملف الإعدادات الصحيح والكامل لمشروع Cloudflare Pages
# =========================================================

# wrangler.toml
name = 'orders-worker'

# تاريخ التوافق لضمان عمل الميزات بشكل صحيح
compatibility_date = "2024-08-08"

# يربط قاعدة البيانات D1 بمشروعك
[[d1_databases]]
binding = "DB"
database_name = "main_database"
database_id = "e0efb93b-1a2e-4131-b172-2c81985f9d02"

# يربط غرف الدردشة (Durable Objects) بمشروعك
[[durable_objects.bindings]]
name = "LIVE_CHAT_ROOM"
class_name = "LiveChatRoom"
# هذا السطر يخبر Pages أن كود غرفة الدردشة موجود في هذا المشروع نفسه
script_name = "khadamat"