name = "khadamat-worker"
main = "src/index.ts"
compatibility_date = "2025-07-20"

# ربط KV Namespace - لازم تغير id برقم KV الخاص بك من Cloudflare
kv_namespaces = [
  { binding = "KV", id = "35f8849f386b48028940a5e54df76258" }
]

# لو تبي تضيف إعدادات إضافية مثل بيئة التطوير أو صفحاة البناء تقدر تضيفها هنا
