# File: wrangler.toml

# ุงุณู ุงูู Worker ุงูุฎุงุต ุจู
name = "orders-worker"

# ุงูููู ุงูุฑุฆูุณู ุงูุฐู ุณูุจุฏุฃ ููู ุงูู Worker
main = "index.js"

# ุชุงุฑูุฎ ุงูุชูุงูู
compatibility_date = "2025-07-20"

# --- โ ุฑุจุท ูุงุนุฏุฉ ุงูุจูุงูุงุช ---
[[d1_databases]]
binding = "DB"
database_name = "main_database"
database_id = "e0efb93b-1a2e-4131-b172-2c81985f9d02"
# --- โโโ ุฑุจุท ูุฎุฒู ุงููููุงุช (R2 Bucket) ---
[[r2_buckets]]
binding = "RECEIPTS_BUCKET"  # ูุฐุง ูู ุงูุงุณู ุงูุฐู ูุณุชุฎุฏูู ุงูููุฏ
bucket_name = "khadamatuk-receipts" # ุชู ุฅุถุงูุฉ ุงุณู ุงููุฎุฒู ุงูุตุญูุญ  
# ... (ุงูุฅุนุฏุงุฏุงุช ุงูููุฌูุฏุฉ ูุณุจููุง ุชุจูู ููุง ูู)

# --- โโโ ุฃุถู ูุฐุง ุงูุฌุฒุก ูุชุนุฑูู ุงููุชุบูุฑุงุช ---
[vars]
R2_PUBLIC_URL = "https://pub-3744e16474fa47dba751a996a877f277.r2.dev" # ๐ง ุงุณุชุจุฏู ูุฐุง ุจุงูุฑุงุจุท ุงูุนุงู ููุฎุฒู R2 ุงูุฎุงุต ุจู