# --- الإعدادات الأساسية للـ Worker ---
name = "technical-support-dashboard"
main = "src/index.js"
compatibility_date = "2025-07-01"

# --- إعدادات الربط بمشروع Pages ---
[pages_build]
# هذا هو اسم المجلد الذي يحتوي على ملفاتك (HTML, CSS, etc.)
# إذا كانت ملفاتك في المجلد الرئيسي، استخدم "."
# إذا كانت في مجلد public، استخدم "public"
upload_dir = "."

# --- ربط قاعدة البيانات D1 ---
[[d1_databases]]
binding = "DB"
database_name = "main_database"
database_id = "e0efb93b-1a2e-4131-b172-2c81985f9d02"

# --- ربط مساحة التخزين R2 ---
[[r2_buckets]]
binding = "RECEIPTS_BUCKET"
bucket_name = "khadamatuk-receipts"

# --- ربط الكائنات الدائمة (Durable Objects) ---
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[migrations]
tag = "v1"
new_classes = ["ChatRoom"]

# --- قاعدة التوجيه الحاسمة لحل المشكلة ---
[[pages.functions.routes]]
include = ["/api/*"]
exclude = []