name: Cleanup Old Deployments

# This workflow can be triggered manually or when this file is pushed.
on:
  push:
    paths:
      - '.github/workflows/cleanup.yml'
  workflow_dispatch:

jobs:
  cleanup:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install the latest version of Wrangler
      - name: Install Wrangler
        run: npm install -g wrangler@latest

      # Step 2: List all deployments, parse their IDs, and delete them one by one
      - name: List and Delete Deployments
        run: |
          echo "Fetching deployment list for project 'khadamat'..."
          
          # Get the list of deployment IDs, skipping the header lines
          DEPLOYMENT_IDS=$(npx wrangler pages deployment list --project-name=khadamat | awk 'NR > 3 {print $1}')
          
          # Check if there are any deployments to delete
          if [ -z "$DEPLOYMENT_IDS" ]; then
            echo "No deployments found to delete. Exiting."
            exit 0
          fi
          
          echo "Starting deletion process..."
          
          # Loop through each ID and delete it
          echo "$DEPLOYMENT_IDS" | while IFS= read -r id; do
            echo "--> Deleting deployment: $id"
            npx wrangler pages deployment delete "$id" --project-name=khadamat --force
          done
          
          echo "Cleanup process complete."
        env:
          # Use the secret token you created
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

