name: Cleanup Old Deployments

on:
  push:
    paths:
      - '.github/workflows/cleanup.yml'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Get Deployment List
        id: get_deployments
        run: |
          DEPLOYMENTS=$(npx wrangler pages deployment list --project-name=khadamat --format=json | jq -r '.[].id')
          echo "deployments=$DEPLOYMENTS" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Delete Deployments
        run: |
          for id in ${{ steps.get_deployments.outputs.deployments }}; do
            echo "Deleting deployment: $id"
            npx wrangler pages deployment delete $id --project-name=khadamat --force
          done
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
